# SPDX-FileCopyrightText: © 2024 Victor Derks
# SPDX-License-Identifier: MIT

version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
